version: '3.7'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express/mongo-express
    ports:
      - 8081:8081
    environment:
      MONGO_URI: mongodb://mongodb:27017/admin
volumes:
  mongodb-data:
